# Numpy Basics

**Defining a list and converting the list into an array using Numpy**

In [6]:
import numpy as np 
mylist = [1,2,3,4]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4]


**Defining a two dimensional list and converting the list into array**

In [ ]:
my2dlist = [[1,2,3,4,5], [2,4,6,8,10], [1,4,9,16,25]]
my2darray = np.array(my2dlist)
print(my2darray)



[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]


**Defining a three dimensional list and converting the list into array**

In [ ]:
my3dlist = [[[1,2,3,4,5], [2,4,6,8,10], [3,6,9,12,15]], [[2,4,6,8,10], [4,8,12,16,20], [6,12,18,24,30]], [[1,3,3,4,5], [3,234,34,3,4], [2323,434,35,35,5]]]
my3darray = np.array(my3dlist)
print(my3darray)

[[[   1    2    3    4    5]
  [   2    4    6    8   10]
  [   3    6    9   12   15]]

 [[   2    4    6    8   10]
  [   4    8   12   16   20]
  [   6   12   18   24   30]]

 [[   1    3    3    4    5]
  [   3  234   34    3    4]
  [2323  434   35   35    5]]]


**Information about previously created arrays**

In [ ]:
print(my3darray.data)

In [ ]:
print(my3darray.shape)

(3, 3, 5)


In [ ]:
print(my3darray.dtype)

int64


In [ ]:
print(my3darray.itemsize)

8


In [ ]:
print(my3darray.strides)

(120, 40, 8)
