# Numpy Basics

**Defining a list and converting the list into an array using Numpy**

In [69]:
import numpy as np 
mylist = [1,2,3,4,5]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4 5]


**Defining a two dimensional list and converting the list into array**

In [70]:
my2dlist = [[1,2,3,4,5], [2,4,6,8,10], [1,4,9,16,25]]
my2darray = np.array(my2dlist)
print(my2darray)



[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]


**Defining a three dimensional list and converting the list into array**

In [71]:
my3dlist = [[[1,2,3,4,5], [2,4,6,8,10], [3,6,9,12,15]], [[2,4,6,8,10], [4,8,12,16,20], [6,12,18,24,30]], [[1,3,3,4,5], [3,234,34,3,4], [2323,434,35,35,5]]]
my3darray = np.array(my3dlist)
print(my3darray)

[[[   1    2    3    4    5]
  [   2    4    6    8   10]
  [   3    6    9   12   15]]

 [[   2    4    6    8   10]
  [   4    8   12   16   20]
  [   6   12   18   24   30]]

 [[   1    3    3    4    5]
  [   3  234   34    3    4]
  [2323  434   35   35    5]]]


**Information about previously created arrays**

array.data displays the memory address

In [72]:
print(my3darray.data)

array.shape displays the size of the array

In [73]:
print(myarray.shape)
print(my2darray.shape)
print(my3darray.shape)

(5,)
(3, 5)
(3, 3, 5)


array.dtype displays the data type of the array

In [74]:
print(myarray.dtype)
print(my2darray.dtype)
print(my3darray.dtype)

int32
int32
int32


array.itemsize displays the size of one element in the given array

In [75]:
print(myarray.itemsize)
print(my2darray.itemsize)
print(my3darray.itemsize)

4
4
4


array.strides displays the no. of bytes should skip to go to the next element

In [76]:
print(myarray.strides)
print(my2darray.strides)
print(my3darray.strides)

(4,)
(20, 4)
(60, 20, 4)


**Creating an array using built-in Numpy functions**

Array of one's \
Syntax: np.ones((shape))

In [77]:
ones = np.ones((5,8))

print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Array of zero's\
Syntax: np.zeros((shape), dtype=data-type)

In [78]:
zeros = np.zeros((2,3,4), dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


Array of random numbers\
Syntax: np.random.random((shape))

In [79]:
thearray=np.random.random((2,5,4))
print(thearray)

[[[0.50078023 0.90164191 0.13162715 0.33221665]
  [0.28949651 0.63500492 0.59753063 0.56180168]
  [0.74527525 0.57387097 0.52954506 0.97993549]
  [0.6636319  0.42784393 0.44299762 0.2226142 ]
  [0.40788081 0.96588422 0.9182469  0.72124518]]

 [[0.56977835 0.74420225 0.10637435 0.9223576 ]
  [0.35661335 0.54290127 0.91994317 0.37352996]
  [0.06976426 0.31798825 0.76412025 0.91513407]
  [0.41306343 0.0761496  0.78225338 0.8473205 ]
  [0.98697365 0.12425478 0.94083174 0.06213639]]]


Empty array with given shape (x,y,z)

Syntax: np.empty((shape))


In [80]:
Empty_array = np.empty((2,3))
print(Empty_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Full array with given shape(2,8) with data '5'

Syntax:  np.full((shape), data_to_be_filled)

In [81]:
full_array= np.full((2,8),5)
print(full_array)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


Array of evenly-spaced values

Syntax: np.arange(start, end, space)

In [82]:
evenly_spaced_array = np.arange(2,25,5)
array2 = np .arange(10, 25, 5)
print(array2)
print(evenly_spaced_array)

[10 15 20]
[ 2  7 12 17 22]


Array of spaced values with given range and no. of elements

Syntax: np.linspace(start, end, no. of elements)

In [83]:
array1=np.linspace(1, 2, 9)
print(array1)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


**Numpy array and file operations**

saving the array to a file
and file is also generated by it

Syntax : np.savetxt("file_name.txt", array , dlimiter = "")

For the below code there is no data.csv file

In [84]:
x = np.arange(1,51,1)


np.savetxt("data.csv", np.c_[x,x], delimiter=',')

Loading the data from the given file

Syntax : np.loadtxt("file_name", )

In [85]:
z= np. loadtxt('data.csv', unpack=True, delimiter=',')
print(type(z))
print(z)

<class 'numpy.ndarray'>
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
  37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
  37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]


In [86]:
my_array= np.genfromtxt("data.out", skip_header=1, filling_values=-999)