# Numpy Basics

**Defining a list and converting the list into an array using Numpy**

In [2]:
import numpy as np 
mylist = [1,2,3,4,5]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4 5]


**Defining a two dimensional list and converting the list into array**

In [3]:
my2dlist = [[1,2,3,4,5], [2,4,6,8,10], [1,4,9,16,25]]
my2darray = np.array(my2dlist)
print(my2darray)



[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]


**Defining a three dimensional list and converting the list into array**

In [4]:
my3dlist = [[[1,2,3,4,5], [2,4,6,8,10], [3,6,9,12,15]], [[2,4,6,8,10], [4,8,12,16,20], [6,12,18,24,30]], [[1,3,3,4,5], [3,234,34,3,4], [2323,434,35,35,5]]]
my3darray = np.array(my3dlist)
print(my3darray)

[[[   1    2    3    4    5]
  [   2    4    6    8   10]
  [   3    6    9   12   15]]

 [[   2    4    6    8   10]
  [   4    8   12   16   20]
  [   6   12   18   24   30]]

 [[   1    3    3    4    5]
  [   3  234   34    3    4]
  [2323  434   35   35    5]]]


**Information about previously created arrays**

array.data displays the memory address

In [5]:
print(my3darray.data)

array.shape displays the size of the array

In [6]:
print(myarray.shape)
print(my2darray.shape)
print(my3darray.shape)

(5,)
(3, 5)
(3, 3, 5)


array.dtype displays the data type of the array

In [7]:
print(myarray.dtype)
print(my2darray.dtype)
print(my3darray.dtype)

int32
int32
int32


array.itemsize displays the size of one element in the given array

In [8]:
print(myarray.itemsize)
print(my2darray.itemsize)
print(my3darray.itemsize)

4
4
4


array.strides displays the no. of bytes should skip to go to the next element

In [9]:
print(myarray.strides)
print(my2darray.strides)
print(my3darray.strides)

(4,)
(20, 4)
(60, 20, 4)


**Creating an array using built-in Numpy functions**

Array of one's \
Syntax: np.ones((shape))

In [10]:
ones = np.ones((5,8))

print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Array of zero's\
Syntax: np.zeros((shape), dtype=data-type)

In [11]:
zeros = np.zeros((2,3,4), dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


Array of random numbers\
Syntax: np.random.random((shape))

In [12]:
thearray=np.random.random((2,5,4))
print(thearray)

[[[0.05110831 0.90676844 0.98694156 0.98243144]
  [0.1929716  0.1770337  0.7425827  0.56176732]
  [0.11424891 0.56244424 0.6284469  0.60902567]
  [0.73996527 0.7963733  0.95897248 0.41507616]
  [0.93306664 0.99383755 0.18157679 0.96243638]]

 [[0.72366386 0.54356714 0.69338229 0.52780408]
  [0.11712556 0.40299154 0.79632622 0.87533578]
  [0.84934097 0.95520771 0.39818102 0.05519947]
  [0.45115538 0.33236388 0.78927897 0.56338068]
  [0.85595495 0.61616818 0.35030514 0.08047658]]]


Empty array with given shape (x,y,z)

Syntax: np.empty((shape))


In [13]:
Empty_array = np.empty((2,3))
print(Empty_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Full array with given shape(2,8) with data '5'

Syntax:  np.full((shape), data_to_be_filled)

In [14]:
full_array= np.full((2,8),5)
print(full_array)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


Array of evenly-spaced values

Syntax: np.arange(start, end, space)

In [15]:
evenly_spaced_array = np.arange(2,25,5)
array2 = np .arange(10, 25, 5)
print(array2)
print(evenly_spaced_array)

[10 15 20]
[ 2  7 12 17 22]


Array of spaced values with given range and no. of elements

Syntax: np.linspace(start, end, no. of elements)

In [16]:
array1=np.linspace(1, 2, 9)
print(array1)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


**Numpy array and file operations**

saving the array to a file
and file is also generated by it

Syntax : np.savetxt("file_name.txt", array , dlimiter = "")

For the below code there is no data.csv file

In [17]:
x = np.arange(1,51,1)


np.savetxt("data.csv", np.c_[x,x], delimiter=',')

Loading the data from the given file

Syntax : np.loadtxt("file_name", )

In [18]:
z= np. loadtxt('data.csv', unpack=True, delimiter=',')
print(type(z))
print(z)

<class 'numpy.ndarray'>
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
  37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
  37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]


In [19]:
my_array= np.genfromtxt("data.out", skip_header=1, filling_values=-999)

In [20]:
my2darray.ndim

2

In [21]:

print(my2darray)
print(my2darray.itemsize)

my2darray.nbytes

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]
4


60

### Accessing the array elements

In [22]:
print(my2darray[0,1])

print(my2darray[0,-2])

print(my2darray[-1,-5])

print(my2darray[0])

2
4
1
[1 2 3 4 5]


In [23]:
print(my2darray[0,:])

print(my2darray[:,2])

[1 2 3 4 5]
[3 6 9]


### Changing the values in an array

In [24]:
my2darray[:,4]= [6,12,36]

print(my2darray)

[[ 1  2  3  4  6]
 [ 2  4  6  8 12]
 [ 1  4  9 16 36]]


In [25]:
my2darray[:,2]=2
print(my2darray)

[[ 1  2  2  4  6]
 [ 2  4  2  8 12]
 [ 1  4  2 16 36]]


In [26]:
my3darray.ndim

3

In [28]:
changed = my2darray.reshape(5,3)
print(changed)

[[ 1  2  2]
 [ 4  6  2]
 [ 4  2  8]
 [12  1  4]
 [ 2 16 36]]
