# Numpy Basics

**Defining a list and converting the list into an array using Numpy**

In [64]:
import numpy as np 
mylist = [1,2,3,4,5]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4 5]


**Defining a two dimensional list and converting the list into array**

In [65]:
my2dlist = [[1,2,3,4,5], [2,4,6,8,10], [1,4,9,16,25]]
my2darray = np.array(my2dlist)
print(my2darray)



[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]


**Defining a three dimensional list and converting the list into array**

In [66]:
my3dlist = [[[1,2,3,4,5], [2,4,6,8,10], [3,6,9,12,15]], [[2,4,6,8,10], [4,8,12,16,20], [6,12,18,24,30]], [[1,3,3,4,5], [3,234,34,3,4], [2323,434,35,35,5]]]
my3darray = np.array(my3dlist)
print(my3darray)

[[[   1    2    3    4    5]
  [   2    4    6    8   10]
  [   3    6    9   12   15]]

 [[   2    4    6    8   10]
  [   4    8   12   16   20]
  [   6   12   18   24   30]]

 [[   1    3    3    4    5]
  [   3  234   34    3    4]
  [2323  434   35   35    5]]]


**Information about previously created arrays**

array.data displays the memory address

In [67]:
print(my3darray.data)

array.shape displays the size of the array

In [68]:
print(myarray.shape)
print(my2darray.shape)
print(my3darray.shape)

(5,)
(3, 5)
(3, 3, 5)


array.dtype displays the data type of the array

In [69]:
print(myarray.dtype)
print(my2darray.dtype)
print(my3darray.dtype)

int32
int32
int32


array.itemsize displays the size of one element in the given array

In [70]:
print(myarray.itemsize)
print(my2darray.itemsize)
print(my3darray.itemsize)

4
4
4


array.strides displays the no. of bytes should skip to go to the next element

In [71]:
print(myarray.strides)
print(my2darray.strides)
print(my3darray.strides)

(4,)
(20, 4)
(60, 20, 4)


**Creating an array using built-in Numpy functions**

Array of one's \
Syntax: np.ones((shape))

In [72]:
ones = np.ones((5,8))

print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Array of zero's\
Syntax: np.zeros((shape), dtype=data-type)

In [73]:
zeros = np.zeros((2,3,4), dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


Array of random numbers\
Syntax: np.random.random((shape))

In [74]:
thearray=np.random.random((2,5,4))
print(thearray)

[[[0.13542374 0.98105454 0.91720429 0.4401473 ]
  [0.65071415 0.99173817 0.54162885 0.91224836]
  [0.0088436  0.68998654 0.63895861 0.36774654]
  [0.22389913 0.46672493 0.64570723 0.3169123 ]
  [0.50317552 0.88191066 0.1438497  0.31177514]]

 [[0.73689249 0.93793396 0.39170937 0.2645575 ]
  [0.2874582  0.48548371 0.03387123 0.15632308]
  [0.30790364 0.58619091 0.08417099 0.63093358]
  [0.23992914 0.8170935  0.50128244 0.71227238]
  [0.80341932 0.061172   0.9393635  0.1453242 ]]]


Empty array with given shape (x,y,z)

Syntax: np.empty((shape))


In [75]:
Empty_array = np.empty((2,3))
print(Empty_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Full array with given shape(2,8) with data '5'

Syntax:  np.full((shape), data_to_be_filled)

In [76]:
full_array= np.full((2,8),5)
print(full_array)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


Array of evenly-spaced values

Syntax: np.arange(start, end, space)

In [77]:
evenly_spaced_array = np.arange(2,25,5)
array2 = np .arange(10, 25, 5)
print(array2)
print(evenly_spaced_array)

[10 15 20]
[ 2  7 12 17 22]


Array of spaced values with given range and no. of elements

Syntax: np.linspace(start, end, no. of elements)

In [78]:
array1=np.linspace(1, 2, 9)
print(array1)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


**Numpy array and file operations**

saving the array to a file
and file is also generated by it

Syntax : np.savetxt("file_name.txt", array , dlimiter = "")

For the below code there is no data.csv file

In [79]:
x = np.arange(1,51,1)


np.savetxt("data.csv", np.c_[x,x], delimiter=',')

Loading the data from the given file

Syntax : np.loadtxt("file_name", )

In [80]:
z= np. loadtxt('data.csv', unpack=True, delimiter=',')
print(type(z))
print(z)

<class 'numpy.ndarray'>
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
  37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
  37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]


In [81]:
my_array= np.genfromtxt("data.out", skip_header=1, filling_values=-999)

#### Prints the which dimension array it is 

In [82]:
my2darray.ndim

2

### Prints the flags of the array

In [83]:
my2darray.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [84]:

print(my2darray)
print(my2darray.itemsize)

my2darray.nbytes

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]
4


60

### Accessing the array elements

In [85]:
print(my2darray[0,1])

print(my2darray[0,-2])

print(my2darray[-1,-5])

print(my2darray[0])

2
4
1
[1 2 3 4 5]


In [86]:
print(my2darray[0,:])

print(my2darray[:,2])

[1 2 3 4 5]
[3 6 9]


### Accessing the values in an array

In [87]:
my2darray[:,4]= [6,12,36]

print(my2darray)

[[ 1  2  3  4  6]
 [ 2  4  6  8 12]
 [ 1  4  9 16 36]]


In [88]:
my2darray[:,2]=2
print(my2darray)

[[ 1  2  2  4  6]
 [ 2  4  2  8 12]
 [ 1  4  2 16 36]]


In [89]:
my3darray.ndim

3

### **Mathematical operations**

In [90]:
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])

addition = a+b
print(addition)

[ 7  9 11 13 15]


In [96]:
add = np.add(a,b)
sub = np.subtract(b,a)
mul = np.multiply(a,b)
div = np.divide(a,b)
rem = np.remainder(a,b)

print(add)
print(sub)
print(mul)
print(div)
print(rem)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]


### Reorganising the array


In [91]:
changed = my2darray.reshape(5,3)
print(changed)

[[ 1  2  2]
 [ 4  6  2]
 [ 4  2  8]
 [12  1  4]
 [ 2 16 36]]


**Creating the vertical stack using two arrays**

In [92]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**Creating the horizontal stack using two arrays**

In [93]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
print(a)
print(a[0:2])
print(a[1:4])
print(my2darray,end="\n\n\n")

print(my2darray[:,2:5])

test = np.identity(6)

print(test)

print(test[2:5,4:])


[1 2 3 4 5]
[1 2]
[2 3 4]
[[ 1  2  2  4  6]
 [ 2  4  2  8 12]
 [ 1  4  2 16 36]]


[[ 2  4  6]
 [ 2  8 12]
 [ 2 16 36]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 0.]]


**Specifying the conditions**

In [119]:
biggerthan = (my2darray>=4)
print(my2darray,end="\n\n\n")
print(my2darray[biggerthan])

[[ 1  2  2  4  6]
 [ 2  4  2  8 12]
 [ 1  4  2 16 36]]


[ 4  6  4  8 12  4 16 36]
