# Numpy Basics

**Defining a list and converting the list into an array using Numpy**

In [76]:
import numpy as np 
mylist = [1,2,3,4,5]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4 5]


**Defining a two dimensional list and converting the list into array**

In [77]:
my2dlist = [[1,2,3,4,5], [2,4,6,8,10], [1,4,9,16,25]]
my2darray = np.array(my2dlist)
print(my2darray)



[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  4  9 16 25]]


**Defining a three dimensional list and converting the list into array**

In [78]:
my3dlist = [[[1,2,3,4,5], [2,4,6,8,10], [3,6,9,12,15]], [[2,4,6,8,10], [4,8,12,16,20], [6,12,18,24,30]], [[1,3,3,4,5], [3,234,34,3,4], [2323,434,35,35,5]]]
my3darray = np.array(my3dlist)
print(my3darray)

[[[   1    2    3    4    5]
  [   2    4    6    8   10]
  [   3    6    9   12   15]]

 [[   2    4    6    8   10]
  [   4    8   12   16   20]
  [   6   12   18   24   30]]

 [[   1    3    3    4    5]
  [   3  234   34    3    4]
  [2323  434   35   35    5]]]


**Information about previously created arrays**

array.data displays the memory address

In [79]:
print(my3darray.data)

array.shape displays the size of the array

In [80]:
print(myarray.shape)
print(my2darray.shape)
print(my3darray.shape)

(5,)
(3, 5)
(3, 3, 5)


array.dtype displays the data type of the array

In [81]:
print(myarray.dtype)
print(my2darray.dtype)
print(my3darray.dtype)

int32
int32
int32


array.itemsize displays the size of one element in the given array

In [82]:
print(myarray.itemsize)
print(my2darray.itemsize)
print(my3darray.itemsize)

4
4
4


array.strides displays the no. of bytes should skip to go to the next element

In [83]:
print(myarray.strides)
print(my2darray.strides)
print(my3darray.strides)

(4,)
(20, 4)
(60, 20, 4)


**Creating an array using built-in Numpy functions**

Array of one's \
Syntax: np.ones((shape))

In [84]:
ones = np.ones((5,8))

print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Array of zero's\
Syntax: np.zeros((shape), dtype=data-type)

In [85]:
zeros = np.zeros((2,3,4), dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


Array of random numbers\
Syntax: np.random.random((shape))

In [86]:
thearray=np.random.random((2,5,4))
print(thearray)

[[[0.79205598 0.33309757 0.34007972 0.44433464]
  [0.20972609 0.35493544 0.26409651 0.3610045 ]
  [0.24286888 0.50805103 0.01834762 0.46562082]
  [0.18763086 0.65477274 0.16263029 0.72462345]
  [0.93674187 0.38439089 0.57700386 0.2563515 ]]

 [[0.24503524 0.88122773 0.77229286 0.63387011]
  [0.95293164 0.78809612 0.62944159 0.69181189]
  [0.82893493 0.51703882 0.50434698 0.09126679]
  [0.91552848 0.89133304 0.95060989 0.0820854 ]
  [0.78729571 0.30848576 0.52420836 0.96031974]]]


Empty array with given shape (x,y,z)

Syntax: np.empty((shape))


In [87]:
Empty_array = np.empty((2,3))
print(Empty_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Full array with given shape(2,8) with data '5'

Syntax:  np.full((shape), data_to_be_filled)

In [88]:
full_array= np.full((2,8),5)
print(full_array)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


Array of evenly-spaced values

Syntax: np.arange(start, end, space)

In [89]:
evenly_spaced_array = np.arange(2,25,5)
array2 = np .arange(10, 25, 5)
print(array2)
print(evenly_spaced_array)

[10 15 20]
[ 2  7 12 17 22]


Array of spaced values with given range and no. of elements

Syntax: np.linspace(start, end, no. of elements)

In [95]:
array1=np.linspace(1, 2, 9)
print(array1)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


**Numpy array and file operations**